import Headers from "@/components/Headers";
import "../css/globals.css";
import Nav from "@/components/Nav";

export const metadata = {
  title: "RealTime",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="flex justify-center items-center min-h-screen bg-gradient-to-t from-[#0D1A4A] to-[#5468A8]">
        <div className="h-180 w-100 bg-white/30 rounded-2xl shadow-2xl relative">
          <Headers />
          {children}
          <Nav />
        </div>
      </body>
    </html>
  );
}
